export const countries = [
    { code: 'AD', label: 'Andorra', phone: '376', name: 'country', value: 'Andorra' },
  { code: 'AE', label: 'United Arab Emirates', phone: '971', name: 'country', value: 'United Arab Emirates' },
  { code: 'AF', label: 'Afghanistan', phone: '93', name: 'country', value: 'Afghanistan' },
  { code: 'AG', label: 'Antigua and Barbuda', phone: '1-268', name: 'country', value: 'Antigua and Barbuda' },
  { code: 'AI', label: 'Anguilla', phone: '1-264', name: 'country', value: 'Anguilla' },
  { code: 'AL', label: 'Albania', phone: '355', name: 'country', value: 'Albania' },
  { code: 'AM', label: 'Armenia', phone: '374', name: 'country', value: 'Armenia' },
  { code: 'AO', label: 'Angola', phone: '244', name: 'country', value: 'Angola' },
  { code: 'AQ', label: 'Antarctica', phone: '672', name: 'country', value: 'Antarctica' },
  { code: 'AR', label: 'Argentina', phone: '54', name: 'country', value: 'Argentina' },
  { code: 'AS', label: 'American Samoa', phone: '1-684', name: 'country', value: 'American Samoa' },
  { code: 'AT', label: 'Austria', phone: '43', name: 'country', value: 'Austria' },
  { code: 'AU', label: 'Australia', phone: '61', name: 'country', value: 'Australia', suggested: true },
  { code: 'AW', label: 'Aruba', phone: '297', name: 'country', value: 'Aruba' },
  { code: 'AX', label: 'Alland Islands', phone: '358', name: 'country', value: 'Alland Islands' },
  { code: 'AZ', label: 'Azerbaijan', phone: '994', name: 'country', value: 'Azerbaijan' },
  { code: 'BA', label: 'Bosnia and Herzegovina', phone: '387', name: 'country', value: 'Bosnia and Herzegovina' },
  { code: 'BB', label: 'Barbados', phone: '1-246', name: 'country', value: 'Barbados' },
  { code: 'BD', label: 'Bangladesh', phone: '880', name: 'country', value: 'Bangladesh' },
  { code: 'BE', label: 'Belgium', phone: '32', name: 'country', value: 'Belgium' },
  { code: 'BF', label: 'Burkina Faso', phone: '226', name: 'country', value: 'Burkina Faso' },
  { code: 'BG', label: 'Bulgaria', phone: '359', name: 'country', value: 'Bulgaria' },
  { code: 'BH', label: 'Bahrain', phone: '973', name: 'country', value: 'Bahrain' },
  { code: 'BI', label: 'Burundi', phone: '257', name: 'country', value: 'Burundi' },
  { code: 'BJ', label: 'Benin', phone: '229', name: 'country', value: 'Benin' },
  { code: 'BL', label: 'Saint Barthelemy', phone: '590', name: 'country', value: 'Saint Barthelemy' },
  { code: 'BM', label: 'Bermuda', phone: '1-441', name: 'country', value: 'Bermuda' },
  { code: 'BN', label: 'Brunei Darussalam', phone: '673', name: 'country', value: 'Brunei Darussalam' },
  { code: 'BO', label: 'Bolivia', phone: '591', name: 'country', value: 'Bolivia' },
  { code: 'BR', label: 'Brazil', phone: '55', name: 'country', value: 'Brazil' },
  { code: 'BS', label: 'Bahamas', phone: '1-242', name: 'country', value: 'Bahamas' },
  { code: 'BT', label: 'Bhutan', phone: '975', name: 'country', value: 'Bhutan' },
  { code: 'BV', label: 'Bouvet Island', phone: '47', name: 'country', value: 'Bouvet Island' },
  { code: 'BW', label: 'Botswana', phone: '267', name: 'country', value: 'Botswana' },
  { code: 'BY', label: 'Belarus', phone: '375', name: 'country', value: 'Belarus' },
  { code: 'BZ', label: 'Belize', phone: '501', name: 'country', value: 'Belize' },
  { code: 'CA', label: 'Canada', phone: '1', name: 'country', value: 'Canada', suggested: true },
  { code: 'CC', label: 'Cocos (Keeling) Islands', phone: '61', name: 'country', value: 'Cocos (Keeling) Islands' }
  ,
  { code: 'CD', label: 'Congo, Democratic Republic of the', phone: '243', name: 'country', value: 'Congo, Democratic Republic of the' },
  { code: 'CF', label: 'Central African Republic', phone: '236', name: 'country', value: 'Central African Republic' },
  { code: 'CG', label: 'Congo, Republic of the', phone: '242', name: 'country', value: 'Congo, Republic of the' },
  { code: 'CH', label: 'Switzerland', phone: '41', name: 'country', value: 'Switzerland' },
  { code: 'CI', label: "Cote d'Ivoire", phone: '225', name: 'country', value: "Cote d'Ivoire" },
  { code: 'CK', label: 'Cook Islands', phone: '682', name: 'country', value: 'Cook Islands' },
  { code: 'CL', label: 'Chile', phone: '56', name: 'country', value: 'Chile' },
  { code: 'CM', label: 'Cameroon', phone: '237', name: 'country', value: 'Cameroon' },
  { code: 'CN', label: 'China', phone: '86', name: 'country', value: 'China' },
  { code: 'CO', label: 'Colombia', phone: '57', name: 'country', value: 'Colombia' },
  { code: 'CR', label: 'Costa Rica', phone: '506', name: 'country', value: 'Costa Rica' },
  { code: 'CU', label: 'Cuba', phone: '53', name: 'country', value: 'Cuba' },
  { code: 'CV', label: 'Cape Verde', phone: '238', name: 'country', value: 'Cape Verde' },
  { code: 'CW', label: 'Curacao', phone: '599', name: 'country', value: 'Curacao' },
  { code: 'CX', label: 'Christmas Island', phone: '61', name: 'country', value: 'Christmas Island' },
  { code: 'CY', label: 'Cyprus', phone: '357', name: 'country', value: 'Cyprus' },
  { code: 'CZ', label: 'Czech Republic', phone: '420', name: 'country', value: 'Czech Republic' },
  { code: 'DE', label: 'Germany', phone: '49', name: 'country', value: 'Germany', suggested: true },
  { code: 'DJ', label: 'Djibouti', phone: '253', name: 'country', value: 'Djibouti' },
  { code: 'DK', label: 'Denmark', phone: '45', name: 'country', value: 'Denmark' },
  { code: 'DM', label: 'Dominica', phone: '1-767', name: 'country', value: 'Dominica' },
  { code: 'DO', label: 'Dominican Republic', phone: '1-809', name: 'country', value: 'Dominican Republic' },
  { code: 'DZ', label: 'Algeria', phone: '213', name: 'country', value: 'Algeria' },
  { code: 'EC', label: 'Ecuador', phone: '593', name: 'country', value: 'Ecuador' },
  { code: 'EE', label: 'Estonia', phone: '372', name: 'country', value: 'Estonia' },
  { code: 'EG', label: 'Egypt', phone: '20', name: 'country', value: 'Egypt' },
  { code: 'EH', label: 'Western Sahara', phone: '212', name: 'country', value: 'Western Sahara' },
  { code: 'ER', label: 'Eritrea', phone: '291', name: 'country', value: 'Eritrea' },
  { code: 'ES', label: 'Spain', phone: '34', name: 'country', value: 'Spain' },
  { code: 'ET', label: 'Ethiopia', phone: '251', name: 'country', value: 'Ethiopia' },
  { code: 'FI', label: 'Finland', phone: '358', name: 'country', value: 'Finland' },
  { code: 'FJ', label: 'Fiji', phone: '679', name: 'country', value: 'Fiji' },
  { code: 'FK', label: 'Falkland Islands (Malvinas)', phone: '500', name: 'country', value: 'Falkland Islands (Malvinas)' },
  { code: 'FM', label: 'Micronesia, Federated States of', phone: '691', name: 'country', value: 'Micronesia, Federated States of' },
  { code: 'FO', label: 'Faroe Islands', phone: '298', name: 'country', value: 'Faroe Islands' },
  { code: 'FR', label: 'France', phone: '33', name: 'country', value: 'France', suggested: true },
  { code: 'GA', label: 'Gabon', phone: '241', name: 'country', value: 'Gabon' },
  { code: 'GB', label: 'United Kingdom', phone: '44', name: 'country', value: 'United Kingdom' },
  { code: 'GD', label: 'Grenada', phone: '1-473', name: 'country', value: 'Grenada' },
  { code: 'GE', label: 'Georgia', phone: '995', name: 'country', value: 'Georgia' },
  { code: 'GF', label: 'French Guiana', phone: '594', name: 'country', value: 'French Guiana' },
  { code: 'GG', label: 'Guernsey', phone: '44', name: 'country', value: 'Guernsey' },
  { code: 'GH', label: 'Ghana', phone: '233', name: 'country', value: 'Ghana' },
  { code: 'GI', label: 'Gibraltar', phone: '350', name: 'country', value: 'Gibraltar' },
  { code: 'GL', label: 'Greenland', phone: '299', name: 'country', value: 'Greenland' },
  { code: 'GM', label: 'Gambia', phone: '220', name: 'country', value: 'Gambia' },
  { code: 'GN', label: 'Guinea', phone: '224', name: 'country', value: 'Guinea' },
  { code: 'GP', label: 'Guadeloupe', phone: '590', name: 'country', value: 'Guadeloupe' },
  { code: 'GQ', label: 'Equatorial Guinea', phone: '240', name: 'country', value: 'Equatorial Guinea' },
  { code: 'GR', label: 'Greece', phone: '30', name: 'country', value: 'Greece' },
  { code: 'GS', label: 'South Georgia and the South Sandwich Islands', phone: '500', name: 'country', value: 'South Georgia and the South Sandwich Islands' },
  { code: 'GT', label: 'Guatemala', phone: '502', name: 'country', value: 'Guatemala' },
  { code: 'GU', label: 'Guam', phone: '1-671', name: 'country', value: 'Guam' },
  { code: 'GW', label: 'Guinea-Bissau', phone: '245', name: 'country', value: 'Guinea-Bissau' },
  { code: 'GY', label: 'Guyana', phone: '592', name: 'country', value: 'Guyana' },
  { code: 'HK', label: 'Hong Kong', phone: '852', name: 'country', value: 'Hong Kong' },
  { code: 'HM', label: 'Heard Island and McDonald Islands', phone: '672', name: 'country', value: 'Heard Island and McDonald Islands' },
  { code: 'HN', label: 'Honduras', phone: '504', name: 'country', value: 'Honduras' },
  { code: 'HR', label: 'Croatia', phone: '385', name: 'country', value: 'Croatia' },
  { code: 'HT', label: 'Haiti', phone: '509', name: 'country', value: 'Haiti' },
  { code: 'HU', label: 'Hungary', phone: '36', name: 'country', value: 'Hungary' },
  { code: 'ID', label: 'Indonesia', phone: '62', name: 'country', value: 'Indonesia' },
  { code: 'IE', label: 'Ireland', phone: '353', name: 'country', value: 'Ireland' },
  { code: 'IL', label: 'Israel', phone: '972', name: 'country', value: 'Israel' },
  { code: 'IM', label: 'Isle of Man', phone: '44', name: 'country', value: 'Isle of Man' },
  { code: 'IN', label: 'India', phone: '91', name: 'country', value: 'India' },
  { code: 'IO', label: 'British Indian Ocean Territory', phone: '246', name: 'country'},
    
  
    { code: 'IQ', label: 'Iraq', phone: '964' },
    {
      code: 'IR',
      label: 'Iran, Islamic Republic of',
      phone: '98',
    },
    { code: 'IS', label: 'Iceland', phone: '354' },
    { code: 'IT', label: 'Italy', phone: '39' },
    { code: 'JE', label: 'Jersey', phone: '44' },
    { code: 'JM', label: 'Jamaica', phone: '1-876' },
    { code: 'JO', label: 'Jordan', phone: '962' },
    {
      code: 'JP',
      label: 'Japan',
      phone: '81',
      suggested: true,
    },
    { code: 'KE', label: 'Kenya', phone: '254' },
    { code: 'KG', label: 'Kyrgyzstan', phone: '996' },
    { code: 'KH', label: 'Cambodia', phone: '855' },
    { code: 'KI', label: 'Kiribati', phone: '686' },
    { code: 'KM', label: 'Comoros', phone: '269' },
    {
      code: 'KN',
      label: 'Saint Kitts and Nevis',
      phone: '1-869',
    },
    {
      code: 'KP',
      label: "Korea, Democratic People's Republic of",
      phone: '850',
    },
    { code: 'KR', label: 'Korea, Republic of', phone: '82' },
    { code: 'KW', label: 'Kuwait', phone: '965' },
    { code: 'KY', label: 'Cayman Islands', phone: '1-345' },
    { code: 'KZ', label: 'Kazakhstan', phone: '7' },
    {
      code: 'LA',
      label: "Lao People's Democratic Republic",
      phone: '856',
    },
    { code: 'LB', label: 'Lebanon', phone: '961' },
    { code: 'LC', label: 'Saint Lucia', phone: '1-758' },
    { code: 'LI', label: 'Liechtenstein', phone: '423' },
    { code: 'LK', label: 'Sri Lanka', phone: '94' },
    { code: 'LR', label: 'Liberia', phone: '231' },
    { code: 'LS', label: 'Lesotho', phone: '266' },
    { code: 'LT', label: 'Lithuania', phone: '370' },
    { code: 'LU', label: 'Luxembourg', phone: '352' },
    { code: 'LV', label: 'Latvia', phone: '371' },
    { code: 'LY', label: 'Libya', phone: '218' },
    { code: 'MA', label: 'Morocco', phone: '212' },
    { code: 'MC', label: 'Monaco', phone: '377' },
    {
      code: 'MD',
      label: 'Moldova, Republic of',
      phone: '373',
    },
    { code: 'ME', label: 'Montenegro', phone: '382' },
    {
      code: 'MF',
      label: 'Saint Martin (French part)',
      phone: '590',
    },
    { code: 'MG', label: 'Madagascar', phone: '261' },
    { code: 'MH', label: 'Marshall Islands', phone: '692' },
    {
      code: 'MK',
      label: 'Macedonia, the Former Yugoslav Republic of',
      phone: '389',
    },
    { code: 'ML', label: 'Mali', phone: '223' },
    { code: 'MM', label: 'Myanmar', phone: '95' },
    { code: 'MN', label: 'Mongolia', phone: '976' },
    { code: 'MO', label: 'Macao', phone: '853' },
    {
      code: 'MP',
      label: 'Northern Mariana Islands',
      phone: '1-670',
    },
    { code: 'MQ', label: 'Martinique', phone: '596' },
    { code: 'MR', label: 'Mauritania', phone: '222' },
    { code: 'MS', label: 'Montserrat', phone: '1-664' },
    { code: 'MT', label: 'Malta', phone: '356' },
    { code: 'MU', label: 'Mauritius', phone: '230' },
    { code: 'MV', label: 'Maldives', phone: '960' },
    { code: 'MW', label: 'Malawi', phone: '265' },
    { code: 'MX', label: 'Mexico', phone: '52' },
    { code: 'MY', label: 'Malaysia', phone: '60' },
    { code: 'MZ', label: 'Mozambique', phone: '258' },
    { code: 'NA', label: 'Namibia', phone: '264' },
    { code: 'NC', label: 'New Caledonia', phone: '687' },
    { code: 'NE', label: 'Niger', phone: '227' },
    { code: 'NF', label: 'Norfolk Island', phone: '672' },
    { code: 'NG', label: 'Nigeria', phone: '234' },
    { code: 'NI', label: 'Nicaragua', phone: '505' },
    { code: 'NL', label: 'Netherlands', phone: '31' },
    { code: 'NO', label: 'Norway', phone: '47' },
    { code: 'NP', label: 'Nepal', phone: '977' },
    { code: 'NR', label: 'Nauru', phone: '674' },
    { code: 'NU', label: 'Niue', phone: '683' },
    { code: 'NZ', label: 'New Zealand', phone: '64' },
    { code: 'OM', label: 'Oman', phone: '968' },
    { code: 'PA', label: 'Panama', phone: '507' },
    { code: 'PE', label: 'Peru', phone: '51' },
    { code: 'PF', label: 'French Polynesia', phone: '689' },
    { code: 'PG', label: 'Papua New Guinea', phone: '675' },
    { code: 'PH', label: 'Philippines', phone: '63' },
    { code: 'PK', label: 'Pakistan', phone: '92' },
    { code: 'PL', label: 'Poland', phone: '48' },
    {
      code: 'PM',
      label: 'Saint Pierre and Miquelon',
      phone: '508',
    },
    { code: 'PN', label: 'Pitcairn', phone: '870' },
    { code: 'PR', label: 'Puerto Rico', phone: '1' },
    {
      code: 'PS',
      label: 'Palestine, State of',
      phone: '970',
    },
    { code: 'PT', label: 'Portugal', phone: '351' },
    { code: 'PW', label: 'Palau', phone: '680' },
    { code: 'PY', label: 'Paraguay', phone: '595' },
    { code: 'QA', label: 'Qatar', phone: '974' },
    { code: 'RE', label: 'Reunion', phone: '262' },
    { code: 'RO', label: 'Romania', phone: '40' },
    { code: 'RS', label: 'Serbia', phone: '381' },
    { code: 'RU', label: 'Russian Federation', phone: '7' },
    { code: 'RW', label: 'Rwanda', phone: '250' },
    { code: 'SA', label: 'Saudi Arabia', phone: '966' },
    { code: 'SB', label: 'Solomon Islands', phone: '677' },
    { code: 'SC', label: 'Seychelles', phone: '248' },
    { code: 'SD', label: 'Sudan', phone: '249' },
    { code: 'SE', label: 'Sweden', phone: '46' },
    { code: 'SG', label: 'Singapore', phone: '65' },
    { code: 'SH', label: 'Saint Helena', phone: '290' },
    { code: 'SI', label: 'Slovenia', phone: '386' },
    {
      code: 'SJ',
      label: 'Svalbard and Jan Mayen',
      phone: '47',
    },
    { code: 'SK', label: 'Slovakia', phone: '421' },
    { code: 'SL', label: 'Sierra Leone', phone: '232' },
    { code: 'SM', label: 'San Marino', phone: '378' },
    { code: 'SN', label: 'Senegal', phone: '221' },
    { code: 'SO', label: 'Somalia', phone: '252' },
    { code: 'SR', label: 'Suriname', phone: '597' },
    { code: 'SS', label: 'South Sudan', phone: '211' },
    {
      code: 'ST',
      label: 'Sao Tome and Principe',
      phone: '239',
    },
    { code: 'SV', label: 'El Salvador', phone: '503' },
    {
      code: 'SX',
      label: 'Sint Maarten (Dutch part)',
      phone: '1-721',
    },
    {
      code: 'SY',
      label: 'Syrian Arab Republic',
      phone: '963',
    },
    { code: 'SZ', label: 'Swaziland', phone: '268' },
    {
      code: 'TC',
      label: 'Turks and Caicos Islands',
      phone: '1-649',
    },
    { code: 'TD', label: 'Chad', phone: '235' },
    {
      code: 'TF',
      label: 'French Southern Territories',
      phone: '262',
    },
    { code: 'TG', label: 'Togo', phone: '228' },
    { code: 'TH', label: 'Thailand', phone: '66' },
    { code: 'TJ', label: 'Tajikistan', phone: '992' },
    { code: 'TK', label: 'Tokelau', phone: '690' },
    { code: 'TL', label: 'Timor-Leste', phone: '670' },
    { code: 'TM', label: 'Turkmenistan', phone: '993' },
    { code: 'TN', label: 'Tunisia', phone: '216' },
    { code: 'TO', label: 'Tonga', phone: '676' },
    { code: 'TR', label: 'Turkey', phone: '90' },
    {
      code: 'TT',
      label: 'Trinidad and Tobago',
      phone: '1-868',
    },
    { code: 'TV', label: 'Tuvalu', phone: '688' },
    {
      code: 'TW',
      label: 'Taiwan',
      phone: '886',
    },
    {
      code: 'TZ',
      label: 'United Republic of Tanzania',
      phone: '255',
    },
    { code: 'UA', label: 'Ukraine', phone: '380' },
    { code: 'UG', label: 'Uganda', phone: '256' },
    {
      code: 'US',
      label: 'United States',
      phone: '1',
      suggested: true,
    },
    { code: 'UY', label: 'Uruguay', phone: '598' },
    { code: 'UZ', label: 'Uzbekistan', phone: '998' },
    {
      code: 'VA',
      label: 'Holy See (Vatican City State)',
      phone: '379',
    },
    {
      code: 'VC',
      label: 'Saint Vincent and the Grenadines',
      phone: '1-784',
    },
    { code: 'VE', label: 'Venezuela', phone: '58' },
    {
      code: 'VG',
      label: 'British Virgin Islands',
      phone: '1-284',
    },
    {
      code: 'VI',
      label: 'US Virgin Islands',
      phone: '1-340',
    },
    { code: 'VN', label: 'Vietnam', phone: '84' },
    { code: 'VU', label: 'Vanuatu', phone: '678' },
    { code: 'WF', label: 'Wallis and Futuna', phone: '681' },
    { code: 'WS', label: 'Samoa', phone: '685' },
    { code: 'XK', label: 'Kosovo', phone: '383' },
    { code: 'YE', label: 'Yemen', phone: '967' },
    { code: 'YT', label: 'Mayotte', phone: '262' },
    { code: 'ZA', label: 'South Africa', phone: '27' },
    { code: 'ZM', label: 'Zambia', phone: '260' },
    { code: 'ZW', label: 'Zimbabwe', phone: '263' },
  ];